language: c

notifications:
  email: false

sudo: required

dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

before_script:
- echo ${LANG}
- echo ${LC_ALL}

script:
  - make CC=${CC} LD=${CC} OPTIM=NONE test && ./tests/test.out
